### ISSUE TITLE
Errors when importing the plugin

### ISSUE THREAD

**Issue by NANAMINER** [yandex-games-plugins/cocos#1] opened 2023-08-28 20:53 UTC
Hello! Please help me! 
I tried to add a plugin to Cocos Creator and got these errors:
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/0b7155f6-2813-4c66-966a-0cc908abf3a0)
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/fc730e42-aa20-4d8d-aa28-64209a567f55)

The buttons "Localization Editor", "Generate Templates", "Check Templates" just don't do anything!

Please help me, what am I doing wrong?

**Comment by koteelok** [comment] 2023-08-29 11:34
Hi, can you tell me more about your environment?

For example:
Cocos Creator version: 3.8.0
Plugin version: 1.0.0

Also, are you sure you downloaded the plugin binary from the [releases page](https://github.com/yandex-games-plugins/cocos/releases/tag/v1.0.1)?

**Comment by koteelok** [comment] 2023-08-29 11:35
Hi, can you tell me more about your environment?

For example:
Cocos Creator version: 3.8.0
Plugin version: 1.0.0

Also, are you sure you downloaded the plugin from the [releases page](https://github.com/yandex-games-plugins/cocos/releases/tag/v1.0.1)?

**Comment by NANAMINER** [comment] 2023-08-29 20:49
Hello again.
As it turned out, the last problem was my fault, I just downloaded the wrong file that was needed. 🤦🏻‍♂️

Now I downloaded the correct version of the plugin, added it to the project, generated templates, everything went well.

But at the stage of integrating the plugin functions into the project code, the following problem arose: VS Code highlights the plugin integration line as "incorrect"
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/a5616323-2141-4cdd-8750-ea417de65257)
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/17d62c72-0131-4938-96c2-5c45d9b9b108)

In the console I get these errors:
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/71b29670-9757-43f3-931f-1098f24017f1)
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/d429a150-5957-45d6-915e-ddd2a038807c)

Moreover, I checked, the file we are accessing exists in the project directory, everything is fine:
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/d7c5ac36-7d37-4c1f-a3e8-40c925f382e6)

Please help me, what am I doing wrong?

My environment:
Cocos Creator version: 3.8.0
Plugin version: 1.0.1

**Comment by koteelok** [comment] 2023-08-30 11:06
Sorry for the delay. The most likely cause of the problem is that you are adding the file extension when importing the script. 

Possible solutions:
* Try simply removing ".ts" from your import.
* Enable the [allowImportingTsExtensions](https://www.typescriptlang.org/tsconfig#allowImportingTsExtensions) flag in your tsconfig.json file.

**Comment by NANAMINER** [comment] 2023-08-30 18:51
Yes, you're right, I added ".ts" to check if that's what's missing. I removed this preposition from the code

I found all the "tsconfig.json" files in the project
![image](https://github.com/yandex-games-plugins/cocos/assets/142423117/ffa929c1-948f-4bc5-b86f-8e4ebe1ef249)
and added "allowImportingTsExtensions": true to each file,

but the error never disappeared

**Comment by koteelok** [comment] 2023-09-02 16:59
If you don't mind, can you send me a project example with an issue reproduced.

I tried several times, but the plugin works perfectly on my end.

**Comment by NANAMINER** [comment] 2023-09-02 17:21
[ClickerAnimeGirls.zip](https://github.com/yandex-games-plugins/cocos/files/12504417/ClickerAnimeGirls.zip)
yes, of course, here are the project files

**Comment by koteelok** [comment] 2023-09-02 21:34
Hello again, seems like it's working if you use **_relative_** path like this:
```import { ysdk } from "../../extensions/yandex-games-sdk/static/assets/ysdk";```

![image](https://github.com/yandex-games-plugins/cocos/assets/65600719/d3f61286-c979-4463-a563-131d9a749c44)

If you really want to use **_absolute_** path for ysdk object, try adding ```"paths": { "*": ["./*"] }``` to tsconfig.json in root of the project like this.

![image](https://github.com/yandex-games-plugins/cocos/assets/65600719/30b7459d-0b8c-439f-b968-637ce9e1f92a)

![image](https://github.com/yandex-games-plugins/cocos/assets/65600719/c2ee8809-562e-4cac-be7e-ce11f0d36882)

I will close the issue on that.

**Closed as completed by koteelok** 2023-09-02 21:34 UTC

**Comment by NANAMINER** [comment] 2023-09-02 22:51
Thank you very much for your help
